# To build a container, you will use the docker build command
# https://docs.docker.com/engine/reference/commandline/build/
#
#   docker build -t <IMAGE TAG> -f Dockerfile.serving .
#   docker build -t <IMAGE TAG> -f Dockerfile.jupyter .
#


# https://docs.docker.com/engine/reference/builder/#from
# You shouldn't need to change this
FROM python:3.9

# https://docs.docker.com/engine/reference/builder/#workdir
# Create and cd into /code as your working directory
WORKDIR /code


# The main docker commands you will find useful:
# 
# Add a file or directory
# https://docs.docker.com/engine/reference/builder/#add
#
#       ADD ./<SOURCE_DIR/FILE> ./<DOCKER_DIR/FILE>
#
# Run a shell command (tip: chain shell commands with && rather than multiple RUN commands)
# https://docs.docker.com/engine/reference/builder/#run
#
#       RUN <SHELL COMMAND>   
#
# Set an environment variable:
# https://docs.docker.com/engine/reference/builder/#env
#
#       ENV <ENV_VAR>=<DEFAULT>
#
# Expose a port
# https://docs.docker.com/engine/reference/builder/#port
#
#       EXPOSE <PORT>
#
# Provide default command for executing container
# https://docs.docker.com/engine/reference/builder/#cmd
#
#       CMD <SHELL COMMAND>


# TODO: install libs
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


# TODO: add code, optionally a default model if you want 
COPY streamlit_app.py ./streamlit_app.py
COPY serving/ ./serving/
COPY ift6758/ ./ift6758/
COPY model_variables.py ./model_variables.py
COPY figures/ ./figures/
RUN pip install -e ./ift6758


# TODO: expose ports (or do this in docker-compose)

##### IMPORTANT #####
# 8501 est le port par défaut pour les applications streamlit, remplacer par le bon port
EXPOSE 8501

# TODO: specify default command - this is not required because you can always specify the command
# either with the docker run command or in the docker-compose file

##### IMPORTANT #####
# Configurer le server port et server address pour streamlit 
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]