import requests
import json
from pathlib import Path
import time


"""
data_acquisition.py
----------------------
Script to retrieve regular and playoff game data per season.

"""


def fetch_data_by_api(game_id : str):
    """
    
    Utility Function - Fetches a json file from NHL API given a Game Id.
    Used for both regular and playoff data.
    -----------------------------------------------------------------------
    Args:
        game_id (String): Takes a Game Id in String Format.
        Game Id is generated by either get_playoff_game_data() or get_regular_game_data().
        See Milestone 1 document and related git link to understand how Game Id is generated (Different for Playoff/Regular).
    -----------------------------------------------------------------------
    Returns:
        "game_id.json" file IF API Request is successful.
        
        (int) -1 IF API Request is unsuccessful -> Used as flag for checks in other functions.
        

    """
    
    url=f"https://api-web.nhle.com/v1/gamecenter/{game_id}/play-by-play"

    try:
        req=requests.get(url)
        file=req.json()
        print(f"Fetched {game_id}")

    except Exception as e:
        #print(f"Error for {game_id}: {e}")
        file=-1

    #Rate limit API to prevent overwhelming/ip ban
    time.sleep(0.5)    

    return file

def get_season_metadata():

    """
    Fetches season metadata (number of games played etc for every season).
    Saves metadata as "season_metadata.json".
    VERY IMPORTANT function that is used to retrieve number of games for regular/playoffs for every season.
    --------------------------------------------------------------------------
    Returns:
        Nothing (Saves a json file if metadata does not exist yet)       

    """

    BASE_DIR=Path("./")
    BASE_DIR.mkdir(parents=True, exist_ok=True)

    file_name=f"season_metadata.json"

    file_path=BASE_DIR/file_name

    if(file_path.exists()):
        print(f"Season Metadata Exists as {file_name}")
        return

    url = "https://api.nhle.com/stats/rest/en/season"
    
    req=requests.get(url)
    file=req.json()

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(file, f, indent=2, ensure_ascii=False)

    print(f"{file_name} Saved")


def retrieve_number_games(year : str, game_type_code: str) -> int:
    """
    Retrieves number of games for playoff/regular season for a specific season.
    Uses "season_metadata.json" to retrieve information.
    -------------------------------------------------------------------------------
    Args:
        year (String): Season for which data needs to retrieve
        game_type_code (String): Type of game: "02" for Regular, "03" for Playoff

    ------------------------------------------------------------------------------
    Returns:
        int : number of games if year (season) and game_type is valid
        int : -1 if parameters are invalid or if "season_metadata.json" is not found.

    """
    
    #Load metadata from file called "season_metadata.json"
    
    BASE_DIR=Path("./")
    BASE_DIR.mkdir(parents=True, exist_ok=True)

    file_name=f"season_metadata.json"
    file_path=BASE_DIR/file_name

    with open(file_path,"r") as f:
        metadata=json.load(f)

    #Metadata is of type dict, key name 'data' contains a list of dictionaries of length 108
    #Retrieve list of dictionaries, loop though to retrieve correct dict, and then retrieve num games
    #key is of format "20162017" for 2016 season, "20202021" for 2020 season and so on...

    list_dict=metadata['data']

    next_year= int (year) + 1
    str_key=f"{year}{next_year}"
    
    for item in list_dict:

        if( str(item['id']) == str_key ):
            
            if(game_type_code=="02"):
                return item['totalRegularSeasonGames']
                
            else:
                return item['totalPlayoffGames']

    return -1 #key not found


def get_playoff_game_data(year : str, num_games : int, SEASON_DIR : Path):
    """
    Called by get_dir_and_data() function.
     
    Generates Game Ids for every Playoff game of a particular season.
    Calls NHL API in fetch_data_by_api() to get data for every Id.
    Implements a cache system that does not call API if data already exists
    Saves every Game Id data as "game_id.json"
    Try-catch block in fetch_data_by_api() handles invalid playoff Ids.
    Try-catch block in fetch_data_by_api() also handles connection errors, etc.
    ------------------------------------------------------------------------------------
    Args:
        (String) year: season
        (int) num_games: number of playoff games for particular season -> retrieved from retrieve_number_games()
        (WindowsPath): Path where data is to be stored ("./data/year/Playoffs/ *.json ")
    
    """

    game_type_code="03"

    #playoff round: 01,02,03,04
    #matchup: 8,4,2,1
    #game number: 1-7
    
    num_rounds = 4

    #Loop through every possible condition
    #try catch block in fetch_data_by_api() will handle invalid playoff Ids.
    
    for round in range(1,num_rounds+1):
        for series in range(1, 2** (num_rounds - round)+1):
                for match in range (1,8):
                    
                    game_id=f"{year}{game_type_code}{round:02d}{series:01d}{match:01d}"
                    
                    file_name=f"{game_id}.json"
        
                    file_path=SEASON_DIR/file_name

                    if(file_path.exists()):
                        #print(f"{file_path} exists")
                        continue
    
                    file = fetch_data_by_api(game_id)
            
                    #If Error in fetching some file, skip and move to next
                    #Error happens because that playoff id is invalid (e.g: series ends in <7 games)
                    if(file==-1):
                        print(f"{game_id} doesn't exist for Playoff Game...Skipped")
                        continue
            
                    with open(file_path, "w", encoding="utf-8") as f:
                        json.dump(file, f, indent=2, ensure_ascii=False)

    print(f"End of Data Acquisition for Season {year} with {num_games} Playoff games")

                    


def get_regular_game_data(year : str, num_games : int, SEASON_DIR : Path):
    """
    Called by get_dir_and_data() function.
    
    Generates Game Ids for every Regular game of a particular season.
    Calls NHL API in fetch_data_by_api() to get data for every Id.
    Implements a cache system that does not call API if data already exists
    Saves every Game Id data as "game_id.json"
    Game Ids are generated in such a way that they're always valid.
    Try-catch block in fetch_data_by_api() handles connection errors, etc.
    ------------------------------------------------------------------------------------
    Args:
        (String) year: season
        (int) num_games: number of regular games for particular season -> retrieved from retrieve_number_games()
        (WindowsPath): Path where data is to be stored ("./data/year/Regular/ *.json ")
    
    """
    
    game_type_code="02"

    for id in range(1, num_games + 1 ):
        
        game_id = f"{year}{game_type_code}{id:04d}"
            
        file_name=f"{game_id}.json"
        
        file_path=SEASON_DIR/file_name
        
        if(file_path.exists()):
            #print(f"{file_path} exists")
            continue
    
        file = fetch_data_by_api(game_id)

        #If Error in fetching some file, stop everything.
        if(file==-1):
            print(f"File error for Regular Game...Aborted")
            break

        with open(file_path, "w", encoding="utf-8") as f:
            json.dump(file, f, indent=2, ensure_ascii=False)

    print(f"End of Data Acquisition for Season {year} with {num_games} Regular games")


def get_dir_and_data( year : str , game_type_code: str):
    """
    Checks and creates respective directories for Regular/Playoff Games
    Fetches Game Data by Calling get_regular_game_data() OR get_playoff_game_data() depending on Game Type.
    ------------------------------------------------------------------------------------
    Args:
        (String) year: season
        (String) game_type_code: Type of game: "02" for Regular, "03" for Playoff
    
    """
    
    num_games=retrieve_number_games(year , game_type_code)

    if(num_games==-1):
        print(f"Invalid Season Id {year}")
        return


    #Create directories if they do not exist
    
    #parents=True Flag: Creates all missing parent directories
    #exist_ok=True Flag: Do not raise error if directories exist
    
    BASE_DIR=Path("./")
    BASE_DIR.mkdir(parents=True, exist_ok=True)

    if game_type_code=="02":
        game_type = "Regular"
    else: game_type = "Playoffs"

    SEASON_DIR=BASE_DIR/year/game_type
    SEASON_DIR.mkdir(parents=True,exist_ok=True)

    if(game_type_code=="02"):
        get_regular_game_data( year, num_games, SEASON_DIR)
    else:
        get_playoff_game_data( year, num_games, SEASON_DIR)


def get_all_regular_game_data(start : int, end : int):
    """
    Starter function for getting Regular Game Data.
    ---------------------------------------------------
    Args:
        (int) start: start season INCLUSIVE
        (int) end: ending season INCLUSIVE
    """

    game_type_regular="02"

    for year in range(start, end + 1):
        str_year=f"{year}"
        get_dir_and_data(str_year , game_type_regular)


def get_all_playoff_game_data(start : int, end : int):
    """
    Starter function for getting Playoff Game Data.
    ---------------------------------------------------
    Args:
        (int) start: start season INCLUSIVE
        (int) end: ending season INCLUSIVE
    """

    game_type_playoff="03"
    
    for year in range (start,end + 1):
        str_year=f"{year}"
        get_dir_and_data(str_year, game_type_playoff)

if __name__ == "__main__":
    
    #get_season_metadata()
    #get_all_playoff_game_data(2016,2024)
    get_all_regular_game_data(2016,2017)
    #get_all_regular_game_data(2016,2024)

    