import pandas as pd
import json
from pathlib import Path
import numpy as np
import os
import requests
import time

from feature_eng_1 import get_engineered_df_by_game


#Ported from Milestone 1 for milestone 3

def get_df_by_game(game_id = 2016020001):

    file = fetch_data_by_api(game_id)

    if(file==-1):
        print(f"File could not be fetched..Aborted")
        return None

    list_of_plays = get_play_by_play_by_game(file)

    df = pd.DataFrame(list_of_plays)

    df_engineered = get_engineered_df_by_game(df, save_csv = True)

    if(df_engineered.loc[0,'game_state'] == 'LIVE'):
        print(f"{game_id} is LIVE")
        
    else: print(f"{game_id} is NOT LIVE")

    return df_engineered
    

def fetch_data_by_api(game_id = 2016020001):
    """
    
    Utility Function - Fetches a json file from NHL API given a Game Id.
    Used for both regular and playoff data.
    -----------------------------------------------------------------------
    Args:
        game_id (String): Takes a Game Id in String Format.
        Game Id is generated by either get_playoff_game_data() or get_regular_game_data().
        See Milestone 1 document and related git link to understand how Game Id is generated (Different for Playoff/Regular).
    -----------------------------------------------------------------------
    Returns:
        "game_id.json" file IF API Request is successful.
        
        (int) -1 IF API Request is unsuccessful -> Used as flag for checks in other functions.
        

    """
    
    url=f"https://api-web.nhle.com/v1/gamecenter/{game_id}/play-by-play"

    try:
        req=requests.get(url)
        file=req.json()
        print(f"Fetched {game_id}")

    except Exception as e:
        #print(f"Error for {game_id}: {e}")
        file=-1

    #Rate limit API to prevent overwhelming/ip ban
    time.sleep(0.5)    

    return file

#Milestone 3
def load_by_game_id(game_id) -> dict :
    """

    Load json file from disk. Make sure data is in same directory as this file.
-----------------------------------------------------------------------------------------------------------------------------------------------
    Args:
        year (int): season
        game_type (int): 2 for regular game, or 3 playoff game
        game_number (int) : function handles conversion to 4 decimal places : e.g 1 -> 001 etc.


    Returns:
        dict: a nested dict containing meta/root data and play-by-play events about the particular game.
------------------------------------------------------------------------------------------------------------------------------------------------

    Reference: Mastering Object-Oriented Python (O’Reilly)
    Reference Link: https://www.oreilly.com/library/view/mastering-object-oriented-python/9781789531367/c34be237-5ccd-4775-a0b0-ec1f7652f7bc.xhtml?
    
    """
    
    #BASE_DIR=Path("./")
    #BASE_DIR=Path("./ift6758/data")

    #BASE_DIR=("C:\\Users\\rambu\\Python Scripts\\Data Science IFT 6758\\Project 2025\\project-template\\ift6758\\data")
    
    #print(BASE_DIR)

    #BASE_DIR = Path(__file__).resolve().parent #fix path issues
    
    #BASE_DIR = DATA_DIR
    

    #game_id=f"{year}{game_type:02d}{game_number:04d}"

    #if (game_type==2):
    #    file_path = BASE_DIR / Path(f"{year}") / Path("Regular") / Path(f"{game_id}.json")
        
    #else: file_path = BASE_DIR / Path(f"{year}") / Path("Playoffs") / Path(f"{game_id}.json")

    file_path = Path(game_id)

    if not file_path.exists():
        print(f"Invalid Id: {game_id}, {file_path}")
        return

    with file_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    return data #Data is of type dict (nested)

def get_season_metadata():

    """
    Fetches season metadata (number of games played etc for every season).
    Saves metadata as "season_metadata.json".
    VERY IMPORTANT function that is used to retrieve number of games for regular/playoffs for every season.
    --------------------------------------------------------------------------
    Returns:
        Nothing (Saves a json file if metadata does not exist yet)       

    """

    BASE_DIR=Path("./")
    BASE_DIR.mkdir(parents=True, exist_ok=True)

    file_name=f"season_metadata.json"

    file_path=BASE_DIR/file_name

    if(file_path.exists()):
        print(f"Season Metadata Exists as {file_name}")
        return

    url = "https://api.nhle.com/stats/rest/en/season"
    
    req=requests.get(url)
    file=req.json()

    with open(file_path, "w", encoding="utf-8") as f:
        json.dump(file, f, indent=2, ensure_ascii=False)

    print(f"{file_name} Saved")


#Ported from tidy_data.py Milestone 1

#Only shots and goals for now, as indicated in Milestone 1 document

def get_play_by_play_by_game(data : dict ) -> list[dict]:

    """

    MOST IMPORTANT FUNCTION FOR 1 GAME
    
    1. Retrieve game metadata FOR 1 GAME.
    2. Loop through & Filter play events and INCLUDE ONLY SHOTS-ON-GOAL AND GOAL (Milestone 1).
    3. Flatten structure so that metadata propagates to every play event.
    4. handles missing values using np.nan.
    5. Do some python dictionary unpacking to alter order of columns in dataframe.

    Called in: 

    Args:
        json dict

    Returns:
        A list of dicts of play-by play events merged with flattened root data -> Flattened structure

    """

    #Get metadata
    game, venue, home, away= get_root_data_by_game(data)

    event_list=['shot-on-goal','goal', 'missed-shot']

    #Retrieve all players details from 'rosterSpots' dict
    player_details = get_player_details(data)
    
    list_of_plays=[]

    plays=data['plays']

    i=0
    
    for play in plays:

        #If event is not a shot-on-goal or goal, skip
        event_type = play['typeDescKey']
        
        if event_type not in event_list:
            continue

        details=play['details']

        event_owner_id=details.get('eventOwnerTeamId', np.nan)

        event_owner_team_name = np.nan

        if not pd.isna(event_owner_id):
            event_owner_team_name = get_event_owner_team_name(event_owner_id,home,away)
        
        goalie_id = details.get('goalieInNetId', np.nan)
        player_id = details.get('shootingPlayerId', np.nan)

        goalie_name = np.nan
        player_name= np.nan

        if not pd.isna(player_id):
            player_name=f"{player_details[player_id]['first_name']} {player_details[player_id]['last_name']}"

        if not pd.isna(goalie_id):
            goalie_name=f"{player_details[goalie_id]['first_name']} {player_details[goalie_id]['last_name']} "
            
        #Player Key name changes in case of a goal 
        
        if (event_type==event_list[1]):
            player_id = details.get('scoringPlayerId', np.nan)
            player_name=f"{player_details[player_id]['first_name']} {player_details[player_id]['last_name']}"
            
        #  **dict: Unpacks dicts in logical order
        
        play_info = {

        **game,
        'period_number': play.get('periodDescriptor').get('number'),
        'period_type': play.get('periodDescriptor').get('periodType'),
        'time_in_period': play.get('timeInPeriod', np.nan),
        'strength': details.get('strength', np.nan),
        'event_type': event_type,
        'shot_type': details.get('shotType', np.nan),
        'x': details.get('xCoord'),
        'y': details.get('yCoord'),
        'player_id': player_id,
        'player_name': player_name,
        'goalie_id': goalie_id,
        'goalie_name': goalie_name,
        'zone_code': details.get('zoneCode'),
        'event_owner_team_id': event_owner_id,
        'event_owner_team_name': event_owner_team_name,
        'home_sog': details.get('homeSOG', np.nan),
        'away_sog':details.get('awaySOG', np.nan),
        'home_defending_side': play.get('homeTeamDefendingSide',np.nan),

        **home,
        **away,
        **venue
        
        } #end of play_info dict

        list_of_plays.append(play_info) #list of dicts
    
    return list_of_plays

def get_player_details(data : dict) -> dict:
    """
    Builds a dict of player & their names etc, and returns it

    Args: json dictionary

    Returns: dictionary mapping player_id to various attributes

    """

    players={}
    
    roster = data['rosterSpots']

    for pl in roster:

        p_id=pl['playerId']
        
        info={}
        info['team_id'] = pl['teamId']
        info['first_name'] = pl['firstName']['default']
        info['last_name'] = pl['lastName']['default']
        info['position_code'] = pl['positionCode']

        players[p_id] = info

    return players


def get_event_owner_team_name(owner_id : int, home: dict , away: dict) -> str:
    """
    Utility function to retrieve team name of offensive players during play0by-play

    Args: Uses 2 of the dictionaries returned by get_root_data_by_game() function.

    Returns: Associated team name as string
        
    """
    
    home_id=home['home_id']
    home_name=home['home_name']

    if (home_id==owner_id):
        return home_name

    return away['away_name']


def get_root_data_by_game( data : dict) -> dict :

    """
    Get root metadata for a game.
    Flattens the nexted json dict structure to include metadata with every play-by-play event.
-------------------------------------------------------------------------------------------------
    Args:
        data (dict) : Takes a json dictionary
        This dictionary is obtained by calling load_by_id() function above
-------------------------------------------------------------------------------------------------
    Returns:
        4 different dictionaries with different metadata about game, venue, home and away teams.
        game_info dict contains the most important information about every game

    """


    #Modified for Milestone 3 -> Live games
    
    game_outcome = data.get("gameOutcome")
    outcome = np.nan

    if game_outcome is None:
        outcome = np.nan
    elif isinstance(game_outcome, dict):
        outcome = game_outcome.get("lastPeriodType", np.nan)
    else:
        outcome = game_outcome

        
    game_info={

        'game_id' : data['id'],
        'season' : data['season'],
        'game_type' : data['gameType'],
        'game_outcome': outcome,
        
        #Added for MIlesone 3 to determine live game status''
        'game_state': data['gameState']
    }

    venue_info={
        
        'venue' :  data['venue']['default'],
        'venue_location' : data['venueLocation']['default']
        #'start_time' : data['startTimeUTC']
    }

    #Set home team dict to a variable to limit nesting
    #Build home team dict

    home=data['homeTeam']
    home_team = {

        'home_id' : home['id'],
        'home_name': home['commonName']['default'],
        'home_location': home['placeName']['default'],
        'home_abrev': home['abbrev'],
        'home_score': home['score']
    }

    #Set away team dict to a variable to limit nesting
    #Build away team dict

    away=data['awayTeam']
    away_team = {

        'away_id' : away['id'],
        'away_name': away['commonName']['default'],
        'away_location': away['placeName']['default'],
        'away_abrev': away['abbrev'],
        'away_score': away['score']
    }
        

    return game_info , venue_info, home_team, away_team

